// <auto-generated />
namespace AngularStuding.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addPasword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPasword));
        
        string IMigrationMetadata.Id
        {
            get { return "201612290815585_addPasword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
